<Project>

  <PropertyGroup>
    <Company>DIGITALL Nature GmbH</Company>
    <Copyright>Copyright (c) DIGITALL Nature GmbH 2024</Copyright>
    <Authors>Marcel Kummerow</Authors>
    <Product>Digitall Power Testing Dataverse</Product>
    <PackageLicenseExpression>MS-RL</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/DIGITALLNature/DigitallTesting</PackageProjectUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageReleaseNotes>https://github.com/DIGITALLNature/DigitallTesting/blob/main/CHANGELOG.md</PackageReleaseNotes>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <SignAssembly>True</SignAssembly>
  </PropertyGroup>

  <PropertyGroup>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <LangVersion>latest</LangVersion>
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
    <Nullable>enable</Nullable>
    <TargetFrameworks>net462;net8.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net462" Version="1.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <Version>1.0.0-beta.4</Version>
    <InformationalVersion>1.0.0-beta.4</InformationalVersion>
    <RepositoryCommit>104069b7ba29422ee8c80c29452b4b9eca97ff99</RepositoryCommit>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)Licence.md" Pack="true" PackagePath=""/>
    <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath=""/>
    <None Include="$(MSBuildThisFileDirectory)CHANGELOG.md" Pack="true" PackagePath=""/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.1.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
