name: Build Digitall.Testing

on:
  push:
    branches-ignore:
      - master
      - beta

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
    - uses: actions/checkout@v3

    - name: Restore DotNet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.x
        cache: true
        cache-dependency-path: '**/packages.lock.json'

    - name: Restore dependencies
      run: dotnet restore --locked-mode

    - name: Build
      run: dotnet build --no-restore

    - name: Run Tests
      run: dotnet run --project tests/Digitall.Testing.Tests --no-build --framework net10.0 -- --report-trx --report-trx-filename test-results.trx

